# Site settings
title: Gergely Turi
email: gergely.turi@utsouthwestern.edu
url: "https://gergelyturi.github.io"
baseurl: ""
description: 
    Gergely Turi's Personal Website
address: 
  "Peter O'Donnell Jr. Brain Institute | 6121 Harry Hines Blvd |
  Office: NS 4.216 |
  Dallas |
  TX, 75390 |
  " 

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'
  
# Google services
google_analytics: UA-141813446-1

# Footer settings
footer: Gergely Turi

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://www.linkedin.com/in/gergely-turi-57028830/
  # - title: booking
  #   url: https://calendar.google.com/calendar/embed?src=glq09ii44hitdbq8fkohuohmms%40group.calendar.google.com&ctz=America%2FNew_York
  # - title: slack
  #   url: https://2pcore.slack.com
  # - title: twitter 
  #   url: https://twitter.com/gergelyturi1  
#  - title: stack-overflow
#   url: http://stackoverflow.com/questions/tagged/jekyll
#  - title: bitbucket
#    url: http://bitbucket.org/jekyll
#  - title: github
#    url: https://github.com/IronSummitMedia/startbootstrap

# Build settings
markdown: kramdown
permalink: pretty
