# Site settings
title: nyspi2pcore
email: gt2253@nyspi.columbia.edu
url: "https://gergelyturi.github.io"
baseurl: ""
description: 
    Preclinical Imaging Core at NYSPI focused on two-photon imaging and related neuroscience tools.
address: 
  "1051 Riverside Drive |
  Office: Kolb Annex, Room: 815 |
  New York |
  NY, 10032 |
  T: 646-774-5027" 

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'
  
# Google services
google_analytics: UA-141813446-1

# Footer settings
footer: Gergely Turi

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: booking
    url: https://calendar.google.com/calendar/embed?src=glq09ii44hitdbq8fkohuohmms%40group.calendar.google.com&ctz=America%2FNew_York
  - title: slack
    url: https://2pcore.slack.com
  - title: twitter 
    url: https://twitter.com/gergelyturi1  
#  - title: stack-overflow
#   url: http://stackoverflow.com/questions/tagged/jekyll
#  - title: bitbucket
#    url: http://bitbucket.org/jekyll
#  - title: github
#    url: https://github.com/IronSummitMedia/startbootstrap

# Build settings
markdown: kramdown
permalink: pretty
